apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: chandanteekinavar/flask:3.2
        env:
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              key: username
              name: env-config
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-secret
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: db-host
              name: env-config
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: db-port
              name: env-config
        # - name: MONGODB_URI
        #   value: mongodb://mongodb.flask.svc.cluster.local:27017/ 
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi