apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.14
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              key: username
              name: env-config
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-secret
        - name: MONGODB_CONF
          value: /etc/mongodb/mongodb.conf
        - name: MONGO_AUTH_ENABLED
          value: "true"
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: database
              name: env-config
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /etc/mongodb
        command: ["mongod", "--config", "/etc/mongodb/mongodb.conf"]
        # command: ["mongod", "--config", "/etc/mongodb/mongodb.conf", "--bind_ip", "0.0.0.0", "--port", "27017"]
      volumes:
      - name: mongodb-config
        configMap:
          name: mongodb-config
      # initContainers:
      # - name: init-mongodb
      #   image: mongo:latest
      #   command: ["mongo", "init-mongodb.mango"]
      #   volumeMounts:
      #   - name: mongodb-data
      #     mountPath: /data/db
      # initContainers:
      # - name: init-mongodb
      #   image: mongo:latest
      #   command: ["bash", "-c"]
      #   args:
      #     - "mongo < init-mongodb.mango"
      #   volumeMounts:
      #     - name: mongodb-data
      #       mountPath: /data/db    
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi